### ISSUE TITLE
Error in training model

### ISSUE THREAD

**Issue by HKABIG** [MarwanMashra/DeepQLearning-Hide-and-Seek#1]
whenever I try to do !python train.py it ends with the error

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1149, in _del_
  File "/usr/local/lib/python3.10/dist-packages/tqdm/rich.py", line 120, in close
  File "/usr/local/lib/python3.10/dist-packages/rich/progress.py", line 1177, in _exit_
  File "/usr/local/lib/python3.10/dist-packages/rich/progress.py", line 1163, in stop
  File "/usr/local/lib/python3.10/dist-packages/rich/live.py", line 155, in stop
  File "/usr/local/lib/python3.10/dist-packages/rich/console.py", line 1137, in line
  File "/usr/local/lib/python3.10/dist-packages/rich/console.py", line 1674, in print
  File "/usr/local/lib/python3.10/dist-packages/rich/console.py", line 1535, in _collect_renderables
  File "/usr/local/lib/python3.10/dist-packages/rich/protocol.py", line 28, in rich_cast
ImportError: sys.meta_path is None, Python is likely shutting down

**Comment by HKABIG** [comment]
@MarwanMashra I Think I have resolve the bug 
This is  due to the python interpreter 
can I make a pull request with a updated code?

**Comment by MarwanMashra** [comment]
Hi, yes you can go a head and make a pull request, I'll review it.
